### DISCUSSION TITLE
Traefik reverse proxy

### DISCUSSION THREAD

**Discussion by junpet** [Difegue/LANraragi#1009] [Q&A] [answered]
Hey!

I selfhost lot of things for some years using traefik as reverse proxy. But for some reason I can't get work lanraragi with traefik. I can't find any errors, I just get 404 when I try to use through my domain. I use debian 12.6, docker v27.0.2, docker compose 2.28.1, traefik v3.0.3. Can you help me or give me tips to debug, because this driving me crazy? The fun part is that, it worked previously, but then I wanted to use it on my local network (adding ports: 3333:3000) as well, and since then it does not works, even if I remove the ports part from the compose file. Let me know if some more information is needed.

I use the following compose file:

```yml
services:
  lanraragi:
    image: difegue/lanraragi
    container_name: lanraragi
    restart: always
    ports:
      - 3333:3000
    environment:
      - LRR_UID=${PUID}
      - LRR_GID=${PGID}
    volumes:
      - lanraragi-content:/home/koyomi/lanraragi/content
      - lanraragi-database:/home/koyomi/lanraragi/database
      - lanraragi-thumb:/home/koyomi/lanraragi/content/thumb
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.lanraragi-rtr.entrypoints=https"
      - "traefik.http.routers.lanraragi-rtr.rule=Host(`lrr.$CLOUDFLARE_DOMAINNAME`)"
      - "traefik.http.routers.lanraragi-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.lanraragi-rtr.middlewares=no-auth-chain@file" # No Authentication
      ## HTTP Services
      - "traefik.http.routers.lanraragi-rtr.service=lanraragi-svc"
      - "traefik.http.services.lanraragi-svc.loadbalancer.server.port=3000"

volumes:
  lanraragi-content:
    driver: local-persist
    driver_opts:
      mountpoint: ${DOCKER_VOLUMES}/lanraragi/content
  lanraragi-database:
    driver: local-persist
    driver_opts:
      mountpoint: ${DOCKER_VOLUMES}/lanraragi/database
  lanraragi-thumb:
    driver: local-persist
    driver_opts:
      mountpoint: ${DOCKER_VOLUMES}/lanraragi/thumb

networks:
  traefik-network:
    external: true
```

For comparison here's the compose file of dokuwiki, which works (and there are 10+ other servicies, which works).

```yml
services:
  dokuwiki:
    image: ghcr.io/linuxserver/dokuwiki
    container_name: dokuwiki
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - dokuwiki-data:/config
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.wiki-rtr.entrypoints=https"
      - "traefik.http.routers.wiki-rtr.rule=Host(`wiki.$CLOUDFLARE_DOMAINNAME`)"
      - "traefik.http.routers.wiki-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.wiki-rtr.middlewares=no-auth-chain@file"
      ## HTTP Services
      - "traefik.http.routers.wiki-rtr.service=wiki-svc"
      - "traefik.http.services.wiki-svc.loadbalancer.server.port=80"

volumes:
  dokuwiki-data:
    driver: local-persist
    driver_opts:
      mountpoint: "${DOCKER_VOLUMES}/dokuwiki"

networks:
  traefik-network:
    external: true
```

Logs for starting the container:

```log
lanraragi  | 2024-06-30T10:41:24.193582001Z s6-rc: info: service s6rc-oneshot-runner: starting
lanraragi  | 2024-06-30T10:41:24.241680321Z s6-rc: info: service s6rc-oneshot-runner successfully started
lanraragi  | 2024-06-30T10:41:24.241728398Z s6-rc: info: service fix-attrs: starting
lanraragi  | 2024-06-30T10:41:24.241741749Z s6-rc: info: service init: starting
lanraragi  | 2024-06-30T10:41:24.252021040Z Starting LANraragi with UID/GID : 1000/1000
lanraragi  | 2024-06-30T10:41:24.258337202Z s6-rc: info: service fix-attrs successfully started
lanraragi  | 2024-06-30T10:41:24.261181759Z s6-rc: info: service legacy-cont-init: starting
lanraragi  | 2024-06-30T10:41:24.272052230Z s6-rc: info: service legacy-cont-init successfully started
lanraragi  | 2024-06-30T10:41:25.210135548Z Fixing permissions, hold on!
lanraragi  | 2024-06-30T10:41:26.497228011Z rm: can't remove '/home/koyomi/lanraragi/public/temp/server.pid': No such file or directory
lanraragi  | 2024-06-30T10:41:26.497706032Z rm: can't remove '/home/koyomi/lanraragi/public/temp/shinobu.pid': No such file or directory
lanraragi  | 2024-06-30T10:41:26.498840069Z rm: can't remove '/home/koyomi/lanraragi/public/temp/shinobu.pid-s6': No such file or directory
lanraragi  | 2024-06-30T10:41:26.499344964Z rm: can't remove '/home/koyomi/lanraragi/public/temp/minion.pid': No such file or directory
lanraragi  | 2024-06-30T10:41:26.500447110Z rm: can't remove '/home/koyomi/lanraragi/public/temp/minion.pid-s6': No such file or directory
lanraragi  | 2024-06-30T10:41:26.502246877Z s6-rc: info: service init successfully started
lanraragi  | 2024-06-30T10:41:26.502639344Z s6-rc: info: service redis: starting
lanraragi  | 2024-06-30T10:41:26.511043666Z s6-rc: info: service redis successfully started
lanraragi  | 2024-06-30T10:41:26.512260699Z s6-rc: info: service lanraragi: starting
lanraragi  | 2024-06-30T10:41:26.522694590Z s6-rc: info: service lanraragi successfully started
lanraragi  | 2024-06-30T10:41:26.523458079Z s6-rc: info: service legacy-services: starting
lanraragi  | 2024-06-30T10:41:26.563362626Z s6-rc: info: service legacy-services successfully started
lanraragi  | 2024-06-30T10:41:27.231066609Z Attempting to create directory /home/koyomi/perl5
lanraragi  | 2024-06-30T10:41:34.237323203Z Server PID will be at /home/koyomi/lanraragi/public/temp/server.pid
lanraragi  | 2024-06-30T10:41:34.237358398Z 
lanraragi  | 2024-06-30T10:41:34.237370135Z 
lanraragi  | 2024-06-30T10:41:34.237381510Z ｷﾀ━━━━━━(ﾟ∀ﾟ)━━━━━━!!!!!
lanraragi  | 2024-06-30T10:41:34.237393674Z Redis error encountered: [KEYS] LOADING Redis is loading the dataset in memory,  at /usr/local/share/perl5/site_perl/Redis.pm line 321.
lanraragi  | 2024-06-30T10:41:34.237405404Z 
lanraragi  | 2024-06-30T10:41:34.237416367Z Trying again in 2 seconds...
lanraragi  | 2024-06-30T10:41:34.237427490Z Redis error encountered: [KEYS] LOADING Redis is loading the dataset in memory,  at /usr/local/share/perl5/site_perl/Redis.pm line 321.
lanraragi  | 2024-06-30T10:41:34.237439218Z 
lanraragi  | 2024-06-30T10:41:34.237450458Z Trying again in 2 seconds...
lanraragi  | 2024-06-30T10:41:34.237461707Z Redis error encountered: [KEYS] LOADING Redis is loading the dataset in memory,  at /usr/local/share/perl5/site_perl/Redis.pm line 321.
lanraragi  | 2024-06-30T10:41:34.237493674Z 
lanraragi  | 2024-06-30T10:41:34.237505291Z Trying again in 2 seconds...
lanraragi  | 2024-06-30T10:41:34.237517031Z [LANraragi] [info] LANraragi 0.9.10 started. (Production Mode)
lanraragi  | 2024-06-30T10:41:34.237528307Z [LANraragi] [info] Plugin Detected: Chaika.moe
lanraragi  | 2024-06-30T10:41:34.237539868Z [LANraragi] [info] Plugin Detected: Chaika.moe api.json
lanraragi  | 2024-06-30T10:41:34.237551823Z [LANraragi] [info] Plugin Detected: ComicInfo
lanraragi  | 2024-06-30T10:41:34.237563466Z [LANraragi] [info] Plugin Detected: Tag Copier
lanraragi  | 2024-06-30T10:41:34.237574981Z [LANraragi] [info] Plugin Detected: Add Timestamp Tag
lanraragi  | 2024-06-30T10:41:34.237586273Z [LANraragi] [info] Plugin Detected: E-Hentai
lanraragi  | 2024-06-30T10:41:34.237597728Z [LANraragi] [info] Plugin Detected: eze
lanraragi  | 2024-06-30T10:41:34.237609185Z [LANraragi] [info] Plugin Detected: FAKKU
lanraragi  | 2024-06-30T10:41:34.371268096Z [LANraragi] [info] Plugin Detected: HentaiAtHome plugin
lanraragi  | 2024-06-30T10:41:34.371315539Z [LANraragi] [info] Plugin Detected: Hdoujin
lanraragi  | 2024-06-30T10:41:34.371328133Z [LANraragi] [info] Plugin Detected: Hentag
lanraragi  | 2024-06-30T10:41:34.371339883Z [LANraragi] [info] Plugin Detected: Hentag Online Lookups
lanraragi  | 2024-06-30T10:41:34.371351675Z [LANraragi] [info] Plugin Detected: Hitomi
lanraragi  | 2024-06-30T10:41:34.371363603Z [LANraragi] [info] Plugin Detected: koromo
lanraragi  | 2024-06-30T10:41:34.371375229Z [LANraragi] [info] Plugin Detected: Koushoku.yaml
lanraragi  | 2024-06-30T10:41:34.371386840Z [LANraragi] [info] Plugin Detected: Mayriad's EH Master Script
lanraragi  | 2024-06-30T10:41:34.371398563Z [LANraragi] [info] Plugin Detected: Pixiv
lanraragi  | 2024-06-30T10:41:34.371410363Z [LANraragi] [info] Plugin Detected: Filename Parsing
lanraragi  | 2024-06-30T10:41:34.371422145Z [LANraragi] [info] Plugin Detected: nHentai
lanraragi  | 2024-06-30T10:41:34.371434087Z [LANraragi] [info] Script Detected: Subfolders to Categories
lanraragi  | 2024-06-30T10:41:34.371445914Z [LANraragi] [info] Script Detected: Source Finder
lanraragi  | 2024-06-30T10:41:34.371457432Z [LANraragi] [info] Script Detected: nHentai Source Converter
lanraragi  | 2024-06-30T10:41:34.371468862Z [LANraragi] [info] Downloader Detected: Chaika.moe Downloader
lanraragi  | 2024-06-30T10:41:34.371480421Z [LANraragi] [info] Downloader Detected: E*Hentai Downloader
lanraragi  | 2024-06-30T10:41:34.371491856Z Minion will use the Redis database at 127.0.0.1:6379/1
lanraragi  | 2024-06-30T10:41:34.371503559Z [LANraragi] [info] Successfully connected to Minion database.
lanraragi  | 2024-06-30T10:41:34.371515276Z [Minion] [info] Starting new Minion worker in subprocess with 4 parallel jobs.
lanraragi  | 2024-06-30T10:41:34.469859850Z [Minion] [info] Minion worker 1354 started
lanraragi  | 2024-06-30T10:41:34.542174976Z [2024-06-30 10:41:34.54188] [1331] [info] Listening at "http://*:3000"
lanraragi  | 2024-06-30T10:41:34.542861445Z [2024-06-30 10:41:34.54268] [1331] [info] Manager 1331 started
lanraragi  | 2024-06-30T10:41:34.542924974Z [LANraragi] [info] Routing done! Ready to receive requests.
lanraragi  | 2024-06-30T10:41:34.542957476Z Web application available at http://127.0.0.1:3000
lanraragi  | 2024-06-30T10:41:34.550933272Z [2024-06-30 10:41:34.55039] [1372] [info] Worker 1372 started
lanraragi  | 2024-06-30T10:41:34.557121055Z [2024-06-30 10:41:34.55627] [1378] [info] Worker 1378 started
lanraragi  | 2024-06-30T10:41:34.562567031Z [2024-06-30 10:41:34.56200] [1384] [info] Worker 1384 started
lanraragi  | 2024-06-30T10:41:34.567687432Z [2024-06-30 10:41:34.56717] [1331] [info] Creating process id file "/home/koyomi/lanraragi/public/temp/server.pid"
lanraragi  | 2024-06-30T10:41:34.568056692Z [2024-06-30 10:41:34.56771] [1390] [info] Worker 1390 started
```

Traefik log:

```json
{
    "ClientAddr": "CENSORED",
    "ClientHost": "CENSORED",
    "ClientPort": "57180",
    "ClientUsername": "-",
    "DownstreamContentSize": 19,
    "DownstreamStatus": 404,
    "Duration": 76248,
    "GzipRatio": 0,
    "OriginContentSize": 0,
    "OriginDuration": 0,
    "OriginStatus": 0,
    "Overhead": 76248,
    "RequestAddr": "lrr.MYDOMAIN.COM",
    "RequestContentSize": 0,
    "RequestCount": 938,
    "RequestHost": "lrr.MYDOMAIN.COM",
    "RequestMethod": "GET",
    "RequestPath": "/",
    "RequestPort": "-",
    "RequestProtocol": "HTTP/2.0",
    "RequestScheme": "https",
    "RetryAttempts": 0,
    "StartLocal": "2024-06-30T10:51:42.474958773Z",
    "StartUTC": "2024-06-30T10:51:42.474958773Z",
    "TLSCipher": "TLS_AES_128_GCM_SHA256",
    "TLSVersion": "1.3",
    "entryPointName": "https",
    "level": "info",
    "msg": "",
    "time": "2024-06-30T10:51:42Z"
}
{
    "ClientAddr": "CENSORED",
    "ClientHost": "CENSORED",
    "ClientPort": "27698",
    "ClientUsername": "-",
    "DownstreamContentSize": 19,
    "DownstreamStatus": 404,
    "Duration": 98191,
    "GzipRatio": 0,
    "OriginContentSize": 0,
    "OriginDuration": 0,
    "OriginStatus": 0,
    "Overhead": 98191,
    "RequestAddr": "lrr.MYDOMAIN.COM",
    "RequestContentSize": 0,
    "RequestCount": 940,
    "RequestHost": "lrr.MYDOMAIN.COM",
    "RequestMethod": "GET",
    "RequestPath": "/favicon.ico",
    "RequestPort": "-",
    "RequestProtocol": "HTTP/2.0",
    "RequestScheme": "https",
    "RetryAttempts": 0,
    "StartLocal": "2024-06-30T10:51:43.317187085Z",
    "StartUTC": "2024-06-30T10:51:43.317187085Z",
    "TLSCipher": "TLS_AES_128_GCM_SHA256",
    "TLSVersion": "1.3",
    "entryPointName": "https",
    "level": "info",
    "msg": "",
    "time": "2024-06-30T10:51:43Z"
}
```
