### ISSUE TITLE
Heavy CPU load and very long runtime when task page_thumbnails for a *.7z with many (>1000) images

### ISSUE THREAD

**Issue by LFsWang** [Difegue/LANraragi#1059]
**LRR Version and OS**
v0.9.21
Docker

**Bug Details**
Put a 7z file with 1000 images into content directory, and open that file in the website to start the page_thumbnails task, and it will use about 2 hours with 100% cpu usage (1 core) to generate 1000 thumbnails .

![image](https://github.com/user-attachments/assets/134775bd-00c8-440c-848b-696716dfb575)

CPU: i5-1340P
RAM: 16GB DDR4 3200Mhz
Disk: NVMe SSD

**Matching Logs**

```
---
args:
- ce4dbc07a118e1a10ecb366fc4094ea56635e855
- 0
attempts: '3'
children: []
created: 2024-08-18T09:23:26.21037Z
delayed: 2024-08-18T09:23:26.21037Z
finished: 2024-08-18T11:04:26.66756Z
id: '751'
notes:
  pages: 1116
  progress: 1116
parents: []
priority: '0'
queue: default
result: ~
retried: ~
retries: '0'
started: 2024-08-18T09:23:26.22036Z
state: finished
task: page_thumbnails
worker: '28'
```

https://github.com/Difegue/LANraragi/blob/v.0.9.21/lib/LANraragi/Utils/Minion.pm#L75
https://github.com/Difegue/LANraragi/blob/v.0.9.21/lib/LANraragi/Utils/Archive.pm#L155

Maybe it need a cache for  `extract_thumbnail` ?
