### ISSUE TITLE
[Bug] cannot remove directory: Permission denied

### ISSUE THREAD

**Issue by gth7754125** [Difegue/LANraragi#354]
**LRR Version and OS**
LRR: 0.73   - docker container version

**Bug Details**
> Error while cleaning Temporary Folder :
> Error: Problem unlinking /home/koyomi/lanraragi/public/temp: cannot remove directory: Permission denied

![image](https://user-images.githubusercontent.com/60313909/96595703-8b2f1f80-131e-11eb-8754-d8ee954fedea.png)

`my docker-compose.yml`
```yml
version: '3'

services:
  lanraragi:
    image: difegue/lanraragi
    container_name: lanraragi
    ports:
      - 3000:3000
    volumes:
      - .\content:/home/koyomi/lanraragi/content
      - .\database:/home/koyomi/lanraragi/database
    restart: always
```
Do i miss some args to set ? 
 I got the same permission problem  when i upload archieves.
