### ISSUE TITLE
EH plugin can not connect to ex gallery

### ISSUE THREAD

**Issue by gth7754125** [Difegue/LANraragi#386]
**LRR Version and OS**
Windows docker container: latest
win10

**Bug Details**
 Error: SSL connect attempt failed at /home/koyomi/lanraragi/script/../lib/LANraragi/Plugin/Metadata/EHentai.pm line 191.

When i search for metadata tags manually, it runs failed.

**docker compose file**
```yml
version: '3'

services:
  lanraragi:
    image: difegue/lanraragi
    container_name: lanraragi
    ports:
      - 3000:3000
    volumes:
      - .\content:/home/koyomi/lanraragi/content
      - .\database:/home/koyomi/lanraragi/database
    restart: always
```
