### ISSUE TITLE
Multi line titles

### ISSUE THREAD

**Issue by darkred3** [Difegue/LANraragi#589]
Currently titles are shown in one, maybe two lines, depending on the theme. It would be nice to have an option to show the whole title all the time, even if that would take 4 or even 5 lines. There's a script called EhxVisited that lets you do that for panda which looks like this:

![677457777](https://user-images.githubusercontent.com/33666486/156646818-e857b0c1-cf68-4cea-98c1-e2ab9036a411.jpg)

**Comment by ndbiaw** [comment]
In `/public/themes/`, select the theme file you are using. At `div.id2 a` add the following value `white-space: initial;`

**Comment by Difegue** [comment]
You can do this through a custom theme or a userstyle by removing `white-space: nowrap` and `height:30px` on `div.id2`.  
It really mangles the interface though, so I won't be making this a stock feature.  

I'd be open to simply removing `white-space: nowrap` (and slightly bumping height to 32px to match the multiples-of-4-rule) , which achieves the same effect as what @ndbiaw mentioned:  
![image](https://user-images.githubusercontent.com/8237712/156849002-172875df-fe92-48c0-a18e-a08b3854e029.png)  
However this breaks ellipsis for text overflow, and I'm not really sure how to fix that. 🤔
(Also keep in mind the full title is always available as a tooltip on hover, as shown here)

**Comment by darkred3** [comment]
Thanks for the help, after trying out a few things I added `height: fit-content;` to `div.id1` and 
```
div.id2 {
  max-height: none;
  min-height: auto;
  margin: auto;
  padding-bottom: 0.25em;
  overflow: visible;
  text-align: center;
  text-overflow: ellipsis;
  vertical-align: middle;
  white-space: nowrap
  width: 97%;
```
Which already looks pretty good, but sadly the "backgrounds" are not really lined up properly. I assume `id1` needs to be edited for that, but I know next to nothing about this. Any idea how to fix it?
![346547541](https://user-images.githubusercontent.com/33666486/156884578-058c8d12-b69f-4b9d-8fd3-befa55e51664.jpg)

Btw the reason I want titles to always show is because I have a lot of non-english galleries and the language of a gallery is usually indicated at the very end so showing titles at all times really helps.

**Comment by siliconfeces** [comment]
You can use https://caniuse.com/?search=line-clamp to allow a set number of rows, while cropping overly long titles in a pretty way. Achtung, not standardized but works in every reasonable browser.

Not exactly what was requested, but may be part of a solution that doesn't fuck up the interface.

Example for two rows using modern.css:
```css

div.id2 {
  height: 30px;
  margin: auto;
  overflow: hidden;
  text-align: center;
  text-overflow: ellipsis;
  vertical-align: middle;
  /* white-space: nowrap; */
  width: 97%;
}

div.id2 a {
  font-weight: bold;
  text-decoration: none;
  /* New stuff below */
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}
```
