### ISSUE TITLE
File move fails with eCryptFS if filename too long

### ISSUE THREAD

**Issue by Pheromir** [Difegue/LANraragi#644]
**LRR Version and OS**
LRR Latest Nightly using Docker (on Synology DSM)

**Bug Details**
Using eCryptFS (which is used by Synology for encryption) limits the filenames to a specific limit (143 bytes, so max 143 ascii chars or less if using unicode chars).
As some archives from specific sites tend to have long filenames, moving the file from the temp directory within the docker container to the final path, which is mostly somewhere mapped to the host fs, fails.

**Matching Logs**
```
---
args:
- https://exhentai.org/g/2xxxx5/5xxxx9
- ~
attempts: '5'
children: []
created: 2022-06-19T10:57:38.93057Z
delayed: 2022-06-19T10:57:38.93057Z
finished: 2022-06-19T10:57:45.46258Z
id: '2024'
notes: {}
parents: []
priority: '1'
queue: default
result:
  category: ~
  id: c8a9f0f8a8a5649fd1239b386b5de3903f075ff5
  message: The file couldn't be moved to your content folder!
  success: 0
  title: Well, here was a very long file name that I kinda prefer not to share publicly
    so i wrote this text to replace the very long file name
  url: exhentai.org/g/2xxxxx5/5xxxxxx9
retried: ~
retries: '0'
started: 2022-06-19T10:57:38.98318Z
state: finished
task: download_url
worker: '120'
```

**Screenshots**
Windows UI language is in german, sorry for that, but that screenshot here just proves that the filename is too long
![grafik](https://user-images.githubusercontent.com/13359741/174478714-80e8e4a6-03f2-4a7d-8b16-2dc5aeda0ae4.png)

**Additional stuff**
There is already a line that shortens the filename in LANraragi::Model::Upload line 185 https://github.com/Difegue/LANraragi/blob/61357739d8230d9ab535090fd4a3b501ba448000/lib/LANraragi/Model/Upload.pm#L185
I don't know how much effort it is, but maybe it could be a good solution to add a setting for the filename to the archive settings, where the user can specify an own length limit that suits their system?

Also the shortening has to be added to uploaded archives, perhaps in LANraragi::Controller::Upload line 27? https://github.com/Difegue/LANraragi/blob/61357739d8230d9ab535090fd4a3b501ba448000/lib/LANraragi/Controller/Upload.pm#L27
Not sure if this is the first location where the archive gets stored on the filesystem, if not the upload could fail earlier.
