### ISSUE TITLE
Deleting archives doesn't delete the files on disk

### ISSUE THREAD

**Issue by CodeOwlTree** [Difegue/LANraragi#680]
<!-- hol up senpai have you checked out the GH Discussions first ? 
Your issue/idea might've already been reported by someone else! 🐱‍👤
https://github.com/Difegue/LANraragi/discussions
->

**LRR Version and OS**

Docker ("latest", so I think:v.0.8.6) running locally on Arch Linux PC.

**Bug Details**

I've noticed that deleting archives doesn't delete the actual files on disk. The comics don't appear in Lanraragi, but they remain on disk. I checked both the local volume and inside the running docker container with ```docker exec -it lanraragi sh```. Files from deleted archives remain in both places.

```
services:
  lanraragi:
    image: 'difegue/lanraragi:latest'
    container_name: 'lanraragi'
    ports:
      - '3000:3000'
    volumes:
      - '/home/my_user/local/lanraragi/content:/home/koyomi/lanraragi/content'
      - '/home/my_user/local/lanraragi/database:/home/koyomi/lanraragi/database'
```
