### ISSUE TITLE
Customizable plugin execution order

### ISSUE THREAD

**Issue by Difegue** [Difegue/LANraragi#930]
This is a follow-up to https://github.com/Difegue/LANraragi/issues/789 -- A generic title update setting leads to conflicts if you have multiple plugins enabled and can't decide which order they're ran in.  

It might also be good to be able to block a plugin from updating archive titles even if the generic setting is toggled on, or move the generic setting to a per-plugin option again(but handled server-side).. god this is complicated

**Comment by khaaansolo** [comment]
I've noticed on the latest version of LRR 0.9.0, you can no longer have eze (or any metadata plugin that attempts to rename) turned ON with Filename Parsing turned ON and get the result of Parsed Name + Metadata tags only. Instead, it looks like File Name Parsing runs, does its job and then immediately gets its archive title replaced by eze archive title.

Annoyingly, the only way I've found around this is to turn on Filename Parsing only as the sole metadata plugin that runs on queue. Once the files are put in with only the Parsed Name, then go to Metadata plugin, TURN OFF 'allow plugins to replace archive titles'. Then go to Batch Operations and run eze. Now eze will place in all the tag info but leave the archive title alone.

**Comment by nuclear06** [comment]
How about adding a field in Redis to store YAML, and using YAML to configure plugins behavior?
But I'm concerned that this add unnecessary complexity.
```yaml
# config.yaml
plugins:
  - Ehentai   # use all info  

  - regexPlugin1    # preprocess title
  - titleOrginPlugin
    exclude: 
      - tags
  - regexPlugin2    # postprocess title

  - nHentai   # only use tags
    exclude: 
      - title
```
